# Generated by Django 4.1 on 2022-09-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_alter_employee_idnumber_alter_employee_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='idNumber',
            new_name='idnum',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='phoneNumber',
            new_name='phoneNum',
        ),
    ]
